# Generated by Django 5.2 on 2025-04-27 05:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='经度')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址描述')),
            ],
            options={
                'verbose_name': '位置',
                'verbose_name_plural': '位置',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='家族ID')),
                ('family_code', models.CharField(max_length=10, unique=True, verbose_name='家族编码')),
                ('name', models.CharField(max_length=100, verbose_name='家族名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='家族描述')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families', to='user.location', verbose_name='家族位置')),
            ],
            options={
                'verbose_name': '家族',
                'verbose_name_plural': '家族',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户名')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='名')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='姓')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('is_staff', models.BooleanField(default=False, verbose_name='工作人员状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='死期')),
                ('milk_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='乳名')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他')], default='other', max_length=10, verbose_name='性别')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('verification_code_expires', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='user.family', verbose_name='家族')),
                ('birth_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_users', to='user.location', verbose_name='出生地')),
                ('burial_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='burial_users', to='user.location', verbose_name='墓地')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('relationship_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='关系ID')),
                ('relationship_type', models.CharField(choices=[('parent', '父母'), ('child', '子女'), ('sibling', '兄弟姐妹'), ('spouse', '配偶')], max_length=50, verbose_name='关系类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('accepted', '已接受'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='关系状态')),
                ('details', models.TextField(blank=True, null=True, verbose_name='关系详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL, verbose_name='关系发起人')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL, verbose_name='关系接收人')),
            ],
        ),
    ]
