# Generated by Django 5.2 on 2025-04-23 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='经度')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址描述')),
            ],
            options={
                'verbose_name': '位置',
                'verbose_name_plural': '位置',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='死期'),
        ),
        migrations.AddField(
            model_name='user',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_father', to=settings.AUTH_USER_MODEL, verbose_name='父亲'),
        ),
        migrations.AddField(
            model_name='user',
            name='milk_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='乳名'),
        ),
        migrations.AddField(
            model_name='user',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_mother', to=settings.AUTH_USER_MODEL, verbose_name='母亲'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='user',
            name='spouses',
            field=models.ManyToManyField(blank=True, related_name='spouse_of', to=settings.AUTH_USER_MODEL, verbose_name='配偶'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_users', to='user.location', verbose_name='出生地'),
        ),
        migrations.AddField(
            model_name='user',
            name='burial_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='burial_users', to='user.location', verbose_name='墓地'),
        ),
    ]
