# Generated by Django 5.2 on 2025-04-26 13:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_verificationcode_user_phone_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthday',
            new_name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='father',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='user',
            name='spouses',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他')], default='other', max_length=10, verbose_name='性别'),
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='家族ID')),
                ('family_code', models.CharField(max_length=10, unique=True, verbose_name='家族编码')),
                ('name', models.CharField(max_length=100, verbose_name='家族名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='家族描述')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families', to='user.location', verbose_name='家族位置')),
            ],
            options={
                'verbose_name': '家族',
                'verbose_name_plural': '家族',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='user.family', verbose_name='家族'),
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('relationship_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='关系ID')),
                ('relationship_type', models.CharField(choices=[('parent', '父母'), ('child', '子女'), ('sibling', '兄弟姐妹'), ('spouse', '配偶')], max_length=50, verbose_name='关系类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('accepted', '已接受'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='关系状态')),
                ('details', models.TextField(blank=True, null=True, verbose_name='关系详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL, verbose_name='关系发起人')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL, verbose_name='关系接收人')),
            ],
        ),
    ]
